### PR TITLE
delete goal agent and relevant code

### PR DESCRIPTION
**Pull request by harryBedfordSL**
## Description

This PR removes the `goal_agent` and all corresponding code related to it, along with any now stale documentation

## Changelog
- Delete `goal_agent`
- Remove test cases
- Remove create_goal utility method
- Remove documentation on goal bot

### CODE REVIEW

**Comment by Ch0live** [comment]
Schema section in the /data directory mentions the goal-bot structure that's probably worth removing

```
# Schema

Currently the schema consists of 1 node. This node is a `Goal` and has 2 properties:

{
    name: "name of goal"
    description: "description of goal"
}
```

**Comment by Ch0live** [comment]
Contributing guide also mentions the `release/goal-bot` branch but that's probably less important to update, just wanted to flag

```
## Branching

Development should follow a consistent branching pattern. 
Major milestones are tracked under a parent `release/<release-desc>` branch, which is merged into using `feature/<change-desc>` and `bugfix/<bug-desc>` branches.

- main
  - release/goal-bot
    - feature/create-director
    - feature/initialise-frontend
    - bugfix/change-markdown-file-link
```

**Review by Ch0live — APPROVED** [review]

**Comment by harryBedfordSL** [comment]
> Schema section in the /data directory mentions the goal-bot structure that's probably worth removing
> 
> ```
> # Schema
> 
> Currently the schema consists of 1 node. This node is a `Goal` and has 2 properties:
> 
> {
>     name: "name of goal"
>     description: "description of goal"
> }
> ```

yeah tbf I think that is worth deleting, will remove now. Can be added back as and when we have a schema

**Comment by harryBedfordSL** [comment]
> Contributing guide also mentions the `release/goal-bot` branch but that's probably less important to update, just wanted to flag
> 
> ```
> ## Branching
> 
> Development should follow a consistent branching pattern. 
> Major milestones are tracked under a parent `release/<release-desc>` branch, which is merged into using `feature/<change-desc>` and `bugfix/<bug-desc>` branches.
> 
> - main
>   - release/goal-bot
>     - feature/create-director
>     - feature/initialise-frontend
>     - bugfix/change-markdown-file-link
> ```

yeah I kept that as thought it was more of an example

**Review by Ch0live — APPROVED** [review]

**Review by bheyman-scottlogic — APPROVED** [review]
Looks good Harry!

**Pull request merged**
